// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.Service.DAL;

namespace Projekt.Service.DAL.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20191103162518_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projekt.Service.DAL.Entities.VehicleMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abrv")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("VehicleMakers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abrv = "A",
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 2,
                            Abrv = "D",
                            Name = "Dacia"
                        },
                        new
                        {
                            Id = 3,
                            Abrv = "B",
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 4,
                            Abrv = "F",
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 5,
                            Abrv = "P",
                            Name = "Peugeot"
                        });
                });

            modelBuilder.Entity("Projekt.Service.DAL.Entities.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abrv")
                        .HasMaxLength(10);

                    b.Property<int>("MakeId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Abrv = "A",
                            MakeId = 1,
                            Name = "S4"
                        },
                        new
                        {
                            Id = 7,
                            Abrv = "A",
                            MakeId = 1,
                            Name = "S6"
                        },
                        new
                        {
                            Id = 8,
                            Abrv = "A",
                            MakeId = 1,
                            Name = "A4"
                        },
                        new
                        {
                            Id = 9,
                            Abrv = "A",
                            MakeId = 1,
                            Name = "A6"
                        },
                        new
                        {
                            Id = 10,
                            Abrv = "A",
                            MakeId = 1,
                            Name = "A8"
                        },
                        new
                        {
                            Id = 11,
                            Abrv = "S",
                            MakeId = 2,
                            Name = "Sandero"
                        },
                        new
                        {
                            Id = 12,
                            Abrv = "D",
                            MakeId = 2,
                            Name = "Duster"
                        },
                        new
                        {
                            Id = 13,
                            Abrv = "S",
                            MakeId = 3,
                            Name = "X5"
                        },
                        new
                        {
                            Id = 14,
                            Abrv = "D",
                            MakeId = 3,
                            Name = "X6"
                        },
                        new
                        {
                            Id = 15,
                            Abrv = "F",
                            MakeId = 4,
                            Name = "Fiesta"
                        },
                        new
                        {
                            Id = 16,
                            Abrv = "M",
                            MakeId = 4,
                            Name = "Mondeo"
                        },
                        new
                        {
                            Id = 17,
                            Abrv = "1",
                            MakeId = 5,
                            Name = "106"
                        },
                        new
                        {
                            Id = 18,
                            Abrv = "2",
                            MakeId = 5,
                            Name = "207"
                        },
                        new
                        {
                            Id = 19,
                            Abrv = "3",
                            MakeId = 5,
                            Name = "306"
                        },
                        new
                        {
                            Id = 20,
                            Abrv = "4",
                            MakeId = 5,
                            Name = "407"
                        });
                });

            modelBuilder.Entity("Projekt.Service.DAL.Entities.VehicleModel", b =>
                {
                    b.HasOne("Projekt.Service.DAL.Entities.VehicleMake", "Make")
                        .WithMany("VehicleModels")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
